<script setup lang="ts">
// Keep this map in sync with app/Support/CategoryIcons.php (admin icon picker).
import {
    Apple,
    Baby,
    Bed,
    Bike,
    BookOpen,
    Cake,
    Camera,
    Car,
    Coffee,
    Cpu,
    CreditCard,
    Dumbbell,
    Film,
    Flower,
    Footprints,
    Fuel,
    Gamepad2,
    Gem,
    Gift,
    Glasses,
    Headphones,
    HeartPulse,
    Home,
    Lamp,
    Laptop,
    Luggage,
    MapPin,
    Monitor,
    Music,
    Package,
    PawPrint,
    Percent,
    Pill,
    Pizza,
    Plane,
    Refrigerator,
    Scissors,
    Shirt,
    ShoppingBag,
    ShoppingCart,
    Smartphone,
    Sofa,
    Sparkles,
    Store,
    Tag,
    TicketPercent,
    ToyBrick,
    TrainFront,
    Trophy,
    Tv,
    Utensils,
    Wallet,
    Watch,
} from '@lucide/vue';
import { computed } from 'vue';
import type { Component } from 'vue';

const props = defineProps<{ name?: string | null; class?: string }>();

const map: Record<string, Component> = {
    tag: Tag,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    gift: Gift,
    percent: Percent,
    'ticket-percent': TicketPercent,
    store: Store,
    package: Package,
    laptop: Laptop,
    smartphone: Smartphone,
    monitor: Monitor,
    headphones: Headphones,
    camera: Camera,
    'gamepad-2': Gamepad2,
    tv: Tv,
    watch: Watch,
    cpu: Cpu,
    shirt: Shirt,
    footprints: Footprints,
    glasses: Glasses,
    gem: Gem,
    home: Home,
    sofa: Sofa,
    lamp: Lamp,
    bed: Bed,
    utensils: Utensils,
    refrigerator: Refrigerator,
    sparkles: Sparkles,
    'heart-pulse': HeartPulse,
    pill: Pill,
    scissors: Scissors,
    flower: Flower,
    apple: Apple,
    coffee: Coffee,
    pizza: Pizza,
    cake: Cake,
    plane: Plane,
    luggage: Luggage,
    'map-pin': MapPin,
    car: Car,
    fuel: Fuel,
    'train-front': TrainFront,
    baby: Baby,
    'toy-brick': ToyBrick,
    'book-open': BookOpen,
    music: Music,
    film: Film,
    dumbbell: Dumbbell,
    bike: Bike,
    trophy: Trophy,
    'paw-print': PawPrint,
    'credit-card': CreditCard,
    wallet: Wallet,
};

const icon = computed<Component>(() =>
    props.name ? (map[props.name] ?? Tag) : Tag,
);
</script>

<template>
    <component :is="icon" :class="props.class" />
</template>
